export default [
  {
    id: 1,
    name: 'Cartoon',
    video: require('./assets/videos/video1.mp4'),
    desc: 'this is video of Cartoon',
    likes: '180k',
    nameimage: require('./assets/img/rating.png'),
    isLiked: false,
  },
  {
    id: 2,
    name: 'Krishnaji',
    video: require('./assets/videos/video2.mp4'),
    desc: 'this is video of Krishnaji',
    likes: '107k',
    nameimage: require('./assets/img/rating.png'),
    isLiked: true,
  },
  {
    id: 3,
    name: 'Ganeshji',
    video: require('./assets/videos/video3.mp4'),
    desc: 'this is video of Ganeshji',
    likes: '187k',
    nameimage: require('./assets/img/rating.png'),
    isLiked: true,
  },
  {
    id: 4,
    name: 'Tom and Jerry',
    video: require('./assets/videos/video4.mp4'),
    desc: 'this is video of Tom and Jerry',
    likes: '189k',
    isLiked: false,
    nameimage: require('./assets/img/rating.png'),
  },
];

//for friends

export const friendsProfileData = [
  {
    name: 'kanchan',
    accountName: 'Kanchan Malviya',
    profileImage: require('./assets/img/rating.png'),
    post: 24,
    followers: 678,
    following: 79,
    follow: true,
  },
  {
    name: 'Raj',
    accountName: 'Raj Malviya',
    profileImage: require('./assets/img/admin.png'),
    post: 20,
    followers: 670,
    following: 89,
    follow: false,
  },
  {
    name: 'Rudrah',
    accountName: 'Rudrah Malviya',
    profileImage: require('./assets/img/admins.png'),
    post: 124,
    followers: 780,
    following: 78,
    follow: true,
  },
  {
    name: 'Saloni',
    accountName: 'Saloni Malviya',
    profileImage: require('./assets/img/donald.jpg'),
    post: 204,
    followers: 665,
    following: 780,
    follow: true,
  },
  {
    name: 'Muskan',
    accountName: 'Muskan Malviya',
    profileImage: require('./assets/img/pics.jpg'),
    post: 74,
    followers: 978,
    following: 799,
    follow: false,
  },
  {
    name: 'Aman',
    accountName: 'Aman Malviya',
    profileImage: require('./assets/img/story.jpg'),
    post: 94,
    followers: 65,
    following: 79,
    follow: true,
  },
];
